# Generated by Django 4.0.3 on 2022-04-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=10)),
                ('Ano', models.IntegerField()),
                ('Cor', models.CharField(max_length=15)),
                ('Placa', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=60)),
                ('Telefone', models.IntegerField(max_length=9)),
                ('Email', models.CharField(max_length=20)),
                ('Senha', models.CharField(max_length=15)),
            ],
        ),
    ]
